# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb748b63ef1bb229e71b380d70af52dea79a07ddd963330ed5e3645ca52990329f6effc7c93f67d5c5850d6cb610c6756670978ca3f7b1a5e0e93517112bc78

test:
  secret_key_base: 5b174045d7c58a1c6269e58ac24634d096a1937e7225b4f58c9ad1f13221b01e34d1850a646c4b255f4e75eee7ce22f6ed2696c2689b8e02f78fda8d9ce0e8ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
